# Generated by Django 5.2.11 on 2026-06-01 05:56

from django.db import migrations


def migrate_addresses(apps, schema_editor):
    CustomerAddress = apps.get_model('home', 'CustomerAddress')
    CustomerProfile = apps.get_model('home', 'CustomerProfile')
    
    for profile in CustomerProfile.objects.all():
        addresses = CustomerAddress.objects.filter(customer=profile)
        default_addr = addresses.filter(is_default=True).first() or addresses.order_by('-id').first()
        
        if default_addr:
            profile.default_address = default_addr.address
            profile.default_lat = default_addr.latitude
            profile.default_long = default_addr.longitude
            profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_booking_booking_address_booking_booking_lat_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_addresses),
        migrations.DeleteModel(
            name='CustomerAddress',
        ),
    ]
