# Generated by Django 5.2.11 on 2026-06-01 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_delete_customeraddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='problem_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
