# Generated by Django 5.2.11 on 2026-06-01 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_alter_booking_problem_description'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_trending', 'trending_order'], name='home_catego_is_tren_a56c7f_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['category_type'], name='home_catego_categor_27f1d2_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='home_produc_price_f458ca_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created_at'], name='home_produc_created_e63807_idx'),
        ),
        migrations.AddIndex(
            model_name='servicemanprofile',
            index=models.Index(fields=['is_active', 'is_approved', 'is_available'], name='home_servic_is_acti_ed24c4_idx'),
        ),
    ]
