# Generated by Django 5.2.11 on 2026-07-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('home', '0051_fcmdevice'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'payment_status'], name='home_bookin_status_f66edb_idx'),
        ),
        migrations.AddIndex(
            model_name='materialorder',
            index=models.Index(fields=['vendor', 'status'], name='home_materi_vendor__bc03da_idx'),
        ),
        migrations.AddIndex(
            model_name='materialorder',
            index=models.Index(fields=['booking', 'status'], name='home_materi_booking_5b773a_idx'),
        ),
        migrations.AddIndex(
            model_name='materialorder',
            index=models.Index(fields=['status', '-created_at'], name='home_materi_status_3eb4b2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='home_user_role_f3ede4_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='home_user_email_536475_idx'),
        ),
    ]
